apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-auth
  template:
    metadata:
      labels:
        app: shop-auth
    spec:
      containers:
        - name: shop-auth
          image: shop-auth:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres:5432/ShopAuth"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "12345"
---
apiVersion: v1
kind: Service
metadata:
  name: shop-auth
spec:
  type: NodePort
  selector:
    app: shop-auth
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
